var CONSTANTS = {};
CONSTANTS.API_PROTOCOL = "http";
CONSTANTS.API_HOST = "csce656-newmedia-rochosc.c9users.io";
CONSTANTS.API_PORT = "8081";
CONSTANTS.API_BASE_URL = CONSTANTS.API_PROTOCOL + "://" + CONSTANTS.API_HOST + ":" + CONSTANTS.API_PORT + "/";
CONSTANTS.VIDEO_FRAME_MAX_SECS = 5;
